/*
  Polargraph 2D Plotter — Motion Control
  ---------------------------------------
  Drives two 28BYJ-48 stepper motors (via ULN2003 driver boards) that wind/
  unwind the two cords holding the pen gondola, plus a servo for pen up/down.

  Motor A (left cord)  -> IN1-IN4
  Motor B (right cord) -> IN5-IN8
  Pen servo             -> PEN_SERVO_PIN
*/

#include <Servo.h>

// ---------- Pen servo ----------
Servo penServo;
const int PEN_SERVO_PIN = 9;
const int PEN_UP_ANGLE   = 90;   // adjust to your linkage
const int PEN_DOWN_ANGLE = 0;    // adjust to your linkage

// ---------- Motor A (left cord) pins ----------
const int A_IN1 = 13;
const int A_IN2 = 12;
const int A_IN3 = 14;
const int A_IN4 = 27;

// ---------- Motor B (right cord) pins ----------
const int B_IN1 = 26;
const int B_IN2 = 25;
const int B_IN3 = 33;
const int B_IN4 = 32;

// Full-step sequence
const int STEP_SEQUENCE[4][4] = {
  {1, 0, 0, 0},
  {0, 1, 0, 0},
  {0, 0, 1, 0},
  {0, 0, 0, 1}
};

const int STEP_DELAY_MS = 3; // lower = faster, but may skip steps

void setup() {
  Serial.begin(115200);

  // Pen servo
  penServo.attach(PEN_SERVO_PIN);
  penUp();

  // Motor A
  pinMode(A_IN1, OUTPUT);
  pinMode(A_IN2, OUTPUT);
  pinMode(A_IN3, OUTPUT);
  pinMode(A_IN4, OUTPUT);

  // Motor B
  pinMode(B_IN1, OUTPUT);
  pinMode(B_IN2, OUTPUT);
  pinMode(B_IN3, OUTPUT);
  pinMode(B_IN4, OUTPUT);

  // TODO: read waypoints (generated by image_to_vectors.py) here,
  // e.g. from Serial, SD card, or a hardcoded array, and call
  // moveTo(x_mm, y_mm) for each one.
}

void loop() {
  // Motion is driven by the waypoint list — nothing to do here.
}

// ---------- Pen control ----------
void penUp() {
  penServo.write(PEN_UP_ANGLE);
  delay(200);
}

void penDown() {
  penServo.write(PEN_DOWN_ANGLE);
  delay(200);
}

// ---------- Low-level stepping ----------
// dirA / dirB: +1 or -1 for winding direction of each cord's motor
void stepBoth(int stepIndexA, int stepIndexB) {
  digitalWrite(A_IN1, STEP_SEQUENCE[stepIndexA][0]);
  digitalWrite(A_IN2, STEP_SEQUENCE[stepIndexA][1]);
  digitalWrite(A_IN3, STEP_SEQUENCE[stepIndexA][2]);
  digitalWrite(A_IN4, STEP_SEQUENCE[stepIndexA][3]);

  digitalWrite(B_IN1, STEP_SEQUENCE[stepIndexB][0]);
  digitalWrite(B_IN2, STEP_SEQUENCE[stepIndexB][1]);
  digitalWrite(B_IN3, STEP_SEQUENCE[stepIndexB][2]);
  digitalWrite(B_IN4, STEP_SEQUENCE[stepIndexB][3]);
}

// Runs `count` full steps on both motors, each independently forward (dir=1)
// or backward (dir=-1), used to change cord lengths and move the gondola.
void runSteps(int count, int dirA, int dirB) {
  static int sA = 0;
  static int sB = 0;

  for (int i = 0; i < count; i++) {
    sA = (sA + dirA + 4) % 4;
    sB = (sB + dirB + 4) % 4;
    stepBoth(sA, sB);
    delay(STEP_DELAY_MS);
  }
}

// ---------- High-level move ----------
// Placeholder: convert a target (x_mm, y_mm) into cord-length deltas and
// step counts based on your frame's motor spacing, then call runSteps()
// for each motor accordingly. Fill in with your triangulation math.
void moveTo(float x_mm, float y_mm) {
  // 1. Compute new left/right cord lengths from (x_mm, y_mm) and motor
  //    mounting positions.
  // 2. Compute the delta vs. current cord lengths -> convert to steps
  //    using your pulley radius and steps-per-revolution.
  // 3. runSteps(steps, dirA, dirB);
}
